[package]
authors = ["Samuel Keiffer <samuelkeiffer@gmail.com>"]
name = "veloren-server-agent"
edition = "2021"
version = "0.1.0"

[features]
worldgen = ["world"]
use-dyn-lib = ["common-dynlib"]
be-dyn-lib = []

[dependencies]
common = { package = "veloren-common", path = "../../common" }
common-base = { package = "veloren-common-base", path = "../../common/base" }
common-dynlib = { package = "veloren-common-dynlib", path = "../../common/dynlib", optional = true }
world = { package = "veloren-world", path = "../../world", optional = true }
rtsim = { package = "veloren-rtsim", path = "../../rtsim" }

specs = { workspace = true, features = ["shred-derive"] }
vek = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
itertools = { workspace = true }
lazy_static = { workspace = true }
tracing = { workspace = true }
