name: linux-arm64 build

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use

      - name: Install cross
        run: |
          cargo install cross

      - name: Build project for ARM64
        run: cross build --release --target aarch64-unknown-linux-gnu --bin veloren-server-cli

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: veloren-server-cli-arm64
          path: target/aarch64-unknown-linux-gnu/release/veloren-server-cli
