name: linux-voxygen build

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Windows 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build -y
          
      - name: Build project
        run: cargo build --release --bin veloren-voxygen

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: voxygen-linux
          path: target/release/veloren-voxygen
